#!/usr/bin/env python

import sys, shlex, re, subprocess

map = []

with open(sys.argv[1]) as f:
    for l in f.readlines():
        tk = l.split(' : ', 1)
        if len(tk) == 2:
            regex = tk[0]
            cmd = shlex.split(tk[1])
            map.append((regex, cmd))
    

while True:
    l = sys.stdin.readline()
    matches = ((re.match(rx, l), cmd) for rx, cmd in map)
    cmds = (cmd for match, cmd in matches if match is not None)

    for cmd in cmds:
        subprocess.call(cmd)

