#!/usr/bin/env bash

set -euo pipefail

priority="70"
timeout="12000"
backend="alsa"
card="hw:$1"
period="128"
np="3"
rate="48000"

# Use remaining params for jackd
shift 1

# Set CPU scaling to ondemand
echo -n ondemand | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor > /dev/null

# So that we can run jackd headless
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
  
# Start
jackd -R -P "$priority" -t "$timeout" \
  -d "$backend" -d "$card" -p "$period" -n "$np" -r "$rate" --midi seq $@ &
