#!/usr/bin/env bash
set -euo pipefail

RECD="$HOME/recordings/$(date +%Y-%m-%d)"
mkdir -p "$RECD"

# Settings
export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH="$PATH:$DIR/bin"
export LOOPS=4
export BINDINGS="$DIR/cfg/fcb1010-pi.slb"
export RECORDINGS="$RECD/track_"
export AUDIO_DEV="US2x2"
export MIDI_DEV="US-2x2"

run-parts --exit-on-error ./init.d
