#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Running as user $USER in dir $DIR"

$DIR/stop-looper 2>/dev/null

set -e
set -u
set -o pipefail

mkdir -p $DIR/log

# Settings
LOOPS=4
BINDINGS="$DIR/fcb1010.slb"
MONOHORN="$DIR/monohorn/bin/monohorn"
SLOONICORN="$DIR/sloonicorn/sloo"

# Start Monohorn - needs root
echo "Starting monohorn"
sudo "$MONOHORN" > $DIR/log/monohorn.log 2>&1 &

# Start sloonicorn - give monohorn time to start
echo "Starting sloonicorn"

# Check for remote sooperlooper
if test ! -z "${SL_OSC_URL:-}"; then

  echo "Using remote SL at: $SL_OSC_URL"
  "$SLOONICORN" -s "$SL_OSC_URL" > $DIR/log/sloonicorn.log 2>&1 &

else

  # Start sloonicorn
  "$SLOONICORN" > $DIR/log/sloonicorn.log 2>&1 &

  # Check if our USB soundcard is connected
  card1="$(aplay -l | awk '/card [1-9]:/ {print $3; exit}')"
  
  # Try and start jack
  if test -z "$card1"; then
    echo "No USB soundcard connected"
    exit 1
  else
    echo "Starting jack: $card1 device"
    $DIR/start-jackd "$card1" > $DIR/log/jack.log 2>&1 &
  fi

  # Give jackd time to start
  jack_wait -w -t 3 2>/dev/null

  if test "$(jack_wait -c)" = "running"; then
    # Start sooperlooper
    echo "Starting sooperlooper with $LOOPS loops"
    sooperlooper -m "$BINDINGS" -l "$LOOPS" > $DIR/log/sooperlooper.log 2>/dev/null &

    # Make jack connections after waiting on sooperlooper
    sleep 2

    echo "Connecting jack ports"
    jack_connect system:capture_1 sooperlooper:common_in_1
    jack_connect system:capture_2 sooperlooper:common_in_2
    jack_connect sooperlooper:common_out_1 system:playback_1
    jack_connect sooperlooper:common_out_2 system:playback_2

    # Make midi connections
    if test ! -z "$(aconnect -o | grep 'USB Midi')"; then
      echo "Connecting USB Midi to sooperlooper"
      aconnect "USB Midi:0" "sooperlooper:0"
    else
      echo "USB Midi adapter not connected"
      exit 1
    fi

    # Set dry level
    echo "Applying SL settings"
    oscsend "${SL_OSC_URL:-osc.udp://localhost:9951}" "/set" "sf" "dry" "1.0"

    # Quantize stuff
    oscsend "${SL_OSC_URL:-osc.udp://localhost:9951}" "/set" "sf" "sync_source" "1.0"
    oscsend "${SL_OSC_URL:-osc.udp://localhost:9951}" "/sl/-1/set" "sf" "quantize" "2.0"
    oscsend "${SL_OSC_URL:-osc.udp://localhost:9951}" "/sl/-1/set" "sf" "sync" "1.0"
    oscsend "${SL_OSC_URL:-osc.udp://localhost:9951}" "/sl/-1/set" "sf" "autoset_latency" "1.0"
  else
    echo "jack couldn't start"
    exit 1
  fi

fi

exit 0
