#!/usr/bin/env bash

priority="70"
timeout="2000"
backend="alsa"
card="hw:$1"
period="64"
np="3"
rate="48000"

# R8 specific settings
if test "$card" = "hw:R8"; then
  np="4"
  period="1024"
fi

# Set CPU scaling to performance
echo -n performance | sudo tee /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor > /dev/null

# So that we can run jackd headless
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket
  
# Start
jackd -R -P "$priority" -t "$timeout" \
  -d "$backend" -d "$card" -p "$period" -n "$np" -r "$rate" --midi seq
