#!/usr/bin/env bash
set -euo pipefail

echo "Starting loopidings"
chronic loopidings &

while test -z "$(aconnect -i | grep loopidings)"; do sleep 1; done

echo "loopidings: connecting MIDI"
aconnect "${MIDI_DEV}:0" "loopidings:0"
